online/carts/urls.py
from django.urls import path
from carts import views
from django.conf.urls.static import static
from django.conf import settings
app_name='carts'
urlpatterns=[
    path('cartindex/',views.cartview,name="cartindex"),
    path('cartlist/<custid>/<lpid>/<lname>/<lmodelno>/<lprice>/<ldiscount>/',views.cartlist,name="cartlist"),
    path('cancelitem/<pk>/',views.cancelitem,name="cancelitem"),
    path('bill/',views.billing,name="bill"),
    path('confirmbill/',views.confirmbill,name="confirmbill"),
    path('buyconfirm/',views.buyconfirm,name="buyconfirm"),
    path('buylist/<custid>/<lpid>/<lname>/<lmodelno>/<lprice>/<ldiscount>/',views.buylist,name="buylist"),
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

online/onlines/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from onlines import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('authen/',include('authen.urls')),
    path('product/',include('product.urls')),
    path('carts/',include('carts.urls')),
    path('',views.welcome,name="welcome")
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

online/carts/models.py
from django.utils import timezone
from django.db import models
from authen.models import registermodel
from product.models import mobiledetail,grocarydetail,clothdetail
#from django.contrib.auth.models import User
from authen.models import registermodel
# Create your models here.

class cartmodel(models.Model):
    coid=models.AutoField(primary_key=True)
    cocustid=models.ForeignKey(registermodel,on_delete=models.CASCADE) #cocustid_id
    coprodid=models.IntegerField()
    copname=models.CharField(max_length=50)
    comodelid=models.CharField(max_length=30)
    coprice=models.FloatField()
    codiscount=models.FloatField()
    

class cartdetails(models.Model):
    caid=models.BigAutoField(primary_key=True)
    cafirst=models.CharField(max_length=50)
    caphone=models.BigIntegerField()
    caemail=models.EmailField(max_length=50)
    caaddress1=models.TextField()
    caaddress2=models.TextField()
    cacountry=models.CharField(max_length=25)
    castate=models.CharField(max_length=25)
    capin=models.IntegerField()
    cashippingbill=models.BooleanField(default=False)

class purchase(cartdetails):
    pid=models.BigAutoField(primary_key=True)
    pdate=models.DateTimeField(default=timezone.now)
    pcustid=models.ForeignKey(registermodel,on_delete=models.CASCADE)
    ptotal=models.FloatField()
    
class payment(purchase):
    paytype=models.CharField(max_length=50)
    paycname=models.CharField(max_length=50)
    paycno=models.BigIntegerField()
    payexpr=models.CharField(max_length=10)
    paycvv=models.CharField(max_length=5)
        
class parchasedetails(models.Model):
    pdid=models.ForeignKey(purchase,on_delete=models.CASCADE)
    pucustid=models.ForeignKey(registermodel,on_delete=models.CASCADE)
    coprodid=models.IntegerField()
    copname=models.CharField(max_length=50)
    comodelid=models.CharField(max_length=30)
    coprice=models.FloatField()
    codiscount=models.FloatField()
    pdate=models.DateTimeField(default=timezone.now)
    

online/carts/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from carts.models import cartmodel, payment,purchase,cartdetails,parchasedetails
from product.models import mobiledetail
from django.db.models import Count,Sum,Max
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/authen/login/')
def cartview(request):
    res=cartmodel.objects.all()
    count=cartmodel.objects.all().aggregate(Count('coid'))
    sum1=cartmodel.objects.all().aggregate(Sum('coprice'))
    return render(request,'cartindex.html',{'res':res,'count':count['coid__count'],'sum':sum1['coprice__sum']})

@login_required(login_url='/authen/login/')
def cartlist(request,custid,lpid,lname,lmodelno,lprice,ldiscount):
    cartmodel.objects.create(cocustid_id=custid,coprodid=lpid,copname=lname,comodelid=lmodelno,coprice=lprice,codiscount=ldiscount)
    return redirect('/product/productview/')

@login_required(login_url='/authen/login/')
def cancelitem(request,pk):
    res=cartmodel.objects.get(coid=pk).delete()
    return redirect('/carts/cartindex/')

details=""
@login_required(login_url='/authen/login/')
def billing(request):
    global details
    if request.method=="POST":
        res=cartmodel.objects.all()
        count=cartmodel.objects.all().aggregate(Count('coid'))
        sum1=cartmodel.objects.all().aggregate(Sum('coprice'))
        details=request.POST
        return render(request,"billpage.html",{'res':res,'count':count['coid__count'],'sum':sum1['coprice__sum'],'d':details})

@login_required(login_url='/authen/login/')
def confirmbill(request):
    if request.method=="POST":
        print("haii")
        cart=cartmodel.objects.all().values('coprodid','copname','comodelid','coprice','codiscount')
        print(cart)
        res=cartmodel.objects.all().values_list('cocustid')
        print(res)
        sum1=cartmodel.objects.all().aggregate(Sum('coprice'))
        print(sum1)
        payment.objects.create(
            cafirst=details['username'], caphone=details['phone'], caemail=details['email'], caaddress1=details['address1'],
            caaddress2=details['address2'], cacountry=details['country'], castate=details['state'], capin=details['pincode'],
            cashippingbill=details['same-address'], paytype=details['paymentMethod'], paycname=details['cardname'], paycno=details['cardno'],
            payexpr=details['expr'], paycvv=details['cvv'], pcustid_id=list(set(res))[0][0], ptotal=sum1['coprice__sum'])
        pu=purchase.objects.all().aggregate(Max("pid"))['pid__max']
        print(pu)
        for i in cart:
            parchasedetails.objects.create(pdid_id=pu, coprodid=i['coprodid'], 
                                           copname=i['copname'], comodelid=i['comodelid'],
                                           coprice=i['coprice'], codiscount=i['codiscount'],pucustid=list(set(res))[0][0])
        cartmodel.objects.all().delete()
        return redirect('/authen/home/')
    return redirect("/carts/cardindex")

buydetails=""
productdetails=""
@login_required(login_url='/authen/login/')
def buylist(request,custid,lpid,lname,lmodelno,lprice,ldiscount):
    global buydetails,productdetails
    details=[custid,lpid,lname,lmodelno,lprice,ldiscount]
    productdetails=details
    if request.method=="POST":
        buydetails=request.POST
        return render(request,"buypage.html",{'b':details,'d':request.POST})
    return render(request,"buycart.html",{'d':details})


def buyconfirm(request):
    if request.method=="POST":
        print("haii")
        payment.objects.create(
            cafirst=buydetails['username'], caphone=buydetails['phone'], caemail=buydetails['email'], caaddress1=buydetails['address1'],
            caaddress2=buydetails['address2'], cacountry=buydetails['country'], castate=buydetails['state'], capin=buydetails['pincode'],
            cashippingbill=buydetails['same-address'], paytype=buydetails['paymentMethod'], paycname=buydetails['cardname'], paycno=buydetails['cardno'],
            payexpr=buydetails['expr'], paycvv=buydetails['cvv'], pcustid_id=int(productdetails[0]), ptotal=productdetails[4])
        pu=purchase.objects.all().aggregate(Max("pid"))['pid__max']
        print(pu)

        print(productdetails)
        print(type(productdetails))
        parchasedetails.objects.create(pdid_id=pu, coprodid=int(productdetails[1]),pucustid_id=int(productdetails[0]),
                                           copname=productdetails[2], comodelid=productdetails[3],
                                           coprice=float(productdetails[4]), codiscount=float(productdetails[5]))
        return redirect('/authen/home/')
    return redirect("/product/productview")

online/carts/templates/billpage.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Confirm billing</title>

    {% include 'partials/bootcss.html'%}
    {% include 'partials/bootjs.html'%}

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<main>
  <form method="POST" action="{% url 'carts:confirmbill' %}">
    {% csrf_token %}
  <div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">Confirm billing</span>
      </a>
    </header>

    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <div class="col-md-6 col-lg-12 order-md-last">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-primary">Your cart</span>
            <span class="badge bg-primary rounded-pill">{{count}}</span>
          </h4>
          <ul class="list-group mb-5">
            {% for i in res %}
            <li class="list-group-item d-flex justify-content-between lh-sm">
              <div>
                <h6 class="my-0">Name:{{i.copname}}</h6>
                <small class="text-muted">Modelno:{{i.comodelid}}</small>
              </div>
              <div>
                <h6 class="my-0">Price:{{i.coprice}}</h6>
                <small class="text-muted">Discount:{{i.codiscount}}</small>
              </div>
              <div>
                <small class="text-muted"> <a href="{% url 'carts:cancelitem' pk=i.coid %}">Cancel</a></small>
              </div>
            </li>
            {% endfor %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total(Rupee)</span>
              <strong>$ {{sum}}</strong>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <div class="col-md-6 col-lg-12 order-md-last">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-primary">Shipping Details</span>
          </h4>
          <ul class="list-group mb-5">
            <li class="list-group-item d-flex justify-content-between lh-sm">
              <div>
                <h5 class="my-0">UserName:{{d.username|title}}</h5>
                <h6 class="my-0">Email:{{d.email}}</h6>
                <h6 class="my-0">Phone:{{d.phone}}</h6>
              </div>
              <div>
                <h6 class="my-0">Address1: {{d.address1}}  | Address2: {{d.address2}}</h6>
                <h6 class="my-0">State: {{d.state}} | country:{{d.country}}</h6>
                <h6 class="my-0">Pincode: {{d.pincode}} </h6>
              </div>
              <div>
                <small class="text-muted"> <a href="{% url 'carts:cartindex'%}">Edit</a></small>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total(Rupee)</span>
              <strong>$ {{sum}}</strong>
            </li>
          </ul>
        </div>
          {% csrf_token %}    
        <a href="{% url 'carts:confirmbill'%}"><button class="btn btn-primary btn-lg" type="Submit">Confirm Billing</button></a>
       </form>    
      </div>
    </div>
    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; 2022
    </footer>
  </div>
</main>


    
  </body>
</html>

online/carts/templates/buypage.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Confirm billing</title>

    {% include 'partials/bootcss.html'%}
    {% include 'partials/bootjs.html'%}

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<main>
  <form method="POST" action="{% url 'carts:buyconfirm'%}">
    {% csrf_token %}
  <div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">Confirm billing</span>
      </a>
    </header>
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <div class="col-md-6 col-lg-12 order-md-last">
              <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-primary">Your cart</span>
                <span class="badge bg-primary rounded-pill">{{1}}</span>
              </h4>
              <ul class="list-group mb-5">
                <li class="list-group-item d-flex justify-content-between lh-sm">
                  <div>
                    <h6 class="my-0">Name:{{b.2}}</h6>
                    <small class="text-muted">Modelno:{{b.3}}</small>
                  </div>
                  <div>
                    <h6 class="my-0">Price:{{b.4}}</h6>
                    <small class="text-muted">Discount:{{b.5}}</small>
                  </div>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>Total(Rupee)</span>
                  <strong>$ {{b.4}}</strong>
                </li>
              </ul>
            </div>
          </div>
      <div class="container-fluid py-5">
        <div class="col-md-6 col-lg-12 order-md-last">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-primary">Shipping Details</span>
          </h4>
          <ul class="list-group mb-5">
            <li class="list-group-item d-flex justify-content-between lh-sm">
              <div>
                <h5 class="my-0">UserName:{{d.username|title}}</h5>
                <h6 class="my-0">Email:{{d.email}}</h6>
                <h6 class="my-0">Phone:{{d.phone}}</h6>
              </div>
              <div>
                <h6 class="my-0">Address1: {{d.address1}}  | Address2: {{d.address2}}</h6>
                <h6 class="my-0">State: {{d.state}} | country:{{d.country}}</h6>
                <h6 class="my-0">Pincode: {{d.pincode}} </h6>
              </div>
              <div>
                <small class="text-muted"> <a href="{% url 'carts:cartindex'%}">Edit</a></small>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total(Rupee)</span>
              <strong>$ {{b.4}}</strong>
            </li>
          </ul>
        </div>
          {% csrf_token %}    
        <button class="btn btn-primary btn-lg" type="Submit">Confirm Billing</button>
       </form>    
      </div>

    </div>
    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; 2022
    </footer>
  </div>
</main>


    
  </body>
</html>

online/carts/templates/cartindex.html
{%load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Cart Page</title>

    {%include 'partials/bootcss.html'%}
    {%include 'partials/bootjs.html'%}
  <link href="{% static 'css/form-validation.css'%}" rel="stylesheet" type=text/css>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  </head>
  <body class="bg-light">
    {%include 'partials/_header.html'%}
<div class="container">
  <main>
    <div class="py-5 text-center">
      <h2>Cart</h2>
    </div>

    <div class="row g-5">
      <div class="col-md-5 col-lg-5 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your cart</span>
          <span class="badge bg-primary rounded-pill">{{count}}</span>
        </h4>
        <ul class="list-group mb-3">
          {% for i in res %}
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Name:{{i.copname}}</h6>
              <small class="text-muted">Modelno:{{i.comodelid}}</small>
            </div>
            <div>
              <h6 class="my-0">Price:{{i.coprice}}</h6>
              <small class="text-muted">Discount:{{i.codiscount}}</small>
            </div>
            <div>
              <small class="text-muted"> <a href="{% url 'carts:cancelitem' pk=i.coid %}">Cancel</a></small>
            </div>
            
          </li>
          {% endfor %}
          <li class="list-group-item d-flex justify-content-between">
            <span>Total(Rupee)</span>
            <strong>$ {{sum}}</strong>
          </li>
        </ul>

        <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </form>
      </div>


      <div class="col-md-8 col-lg-6">
        <h4 class="mb-3">Billing address</h4>
        <form class="needs-validation" action="{% url 'carts:bill' %}" method="POST">
          {%csrf_token%}
          <div class="row g-3">
            
            <div class="col-12">
              <label for="username" class="form-label">Username</label>
              <div class="input-group has-validation">
                <span class="input-group-text">@</span>
                <input type="text" name="username" class="form-control" id="username" placeholder="Username" required>
              <div class="invalid-feedback">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="col-sm-12">
              <label for="phone" class="form-label">Phone</label>
              <input type="number"  name="phone" class="form-control" id="phone" placeholder="enter 10 digit number" value="" required>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted"></span></label>
              <input type="email"  name="email" class="form-control" id="email" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text"  name="address1" class="form-control" id="address" placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
              <input type="text"  name="address2" class="form-control" id="address2" placeholder="Apartment or suite">
            </div>

            <div class="col-md-5">
              <label for="country" class="form-label">Country</label>
              <select name="country" class="form-select" id="country" required>
                <option value="">Choose...</option>
                <option value="US">United States</option>
                <option value="India">India</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-md-4">
              <label for="state" class="form-label">State</label>
              <select class="form-select" name="state" id="state" required>
                <option value="">Choose...</option>
                <option value="California">California</option>
                <option value="Andhra pradesh">Andhra pradesh</option>
                <option value="Karnataka">Karnataka</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid state.
              </div>
            </div>

            <div class="col-md-3">
              <label for="zip" class="form-label">Pin</label>
              <input type="text" name="pincode" class="form-control" id="zip" placeholder="" required>
              <div class="invalid-feedback">
                Pin code required.
              </div>
            </div>
          </div>

          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" name="same-address" class="form-check-input" value="True" id="same-address">
            <label class="form-check-label"  for="same-address">Shipping address is the same as my billing address</label>
          </div>

          <hr class="my-4">

          <h4 class="mb-3">Payment</h4>

          <div class="my-3">
            <div class="form-check">
              <input id="credit" name="paymentMethod" type="radio" value='Credit card' class="form-check-input"checked >
              <label class="form-check-label" for="credit">Credit card</label>
            </div>
            <div class="form-check">
              <input id="debit" name="paymentMethod" type="radio"  value='Debit card' class="form-check-input" >
              <label class="form-check-label" for="debit">Debit card</label>
            </div>
            <div class="form-check">
              <input id="paypal" name="paymentMethod" type="radio"  value='Pay pal' class="form-check-input">
              <label class="form-check-label" for="paypal">PayPal</label>
            </div>
          </div>

          <div class="row gy-3">
            <div class="col-md-6">
              <label for="cc-name" class="form-label">Name on card</label>
              <input type="text" name="cardname" class="form-control" id="cc-name" placeholder="" required>
              <small class="text-muted">Full name as displayed on card</small>
              <div class="invalid-feedback">
                Name on card is required
              </div>
            </div>

            <div class="col-md-6">
              <label for="cc-number" class="form-label">Credit card number</label>
              <input type="text"  name="cardno" class="form-control" id="cc-number" placeholder="" required>
              <div class="invalid-feedback">
                Credit card number is required
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-expiration" class="form-label">Expiration</label>
              <input type="text" name="expr" class="form-control" id="cc-expiration" placeholder="" required>
              <div class="invalid-feedback">
                Expiration date required
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-cvv" class="form-label">CVV</label>
              <input type="text" name="cvv" class="form-control" id="cc-cvv" placeholder="" required>
              <div class="invalid-feedback">
                Security code required
              </div>
            </div>
          </div>

          <hr class="my-4">

          <button  class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
        </form>
      </div>
    </div>
  </main>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2017–2021 Company Name</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>
</div>
      <script src="{% static 'js/form-validation.js' %}" type="text/javascript"></script>
  </body>
</html>