online/carts/urls.py
from django.urls import path
from carts import views
from django.conf.urls.static import static
from django.conf import settings
app_name='carts'
urlpatterns=[
    path('cartindex/',views.cartview,name="cartindex"),
    path('cartlist/<custid>/<lpid>/<lname>/<lmodelno>/<lprice>/<ldiscount>/',views.cartlist,name="cartlist"),
    path('cancelitem/<pk>/',views.cancelitem,name="cancelitem"),
    path('bill/',views.billing,name="bill"),
    path('confirmbill/',views.confirmbill,name="confirmbill"),
    path('buyconfirm/',views.buyconfirm,name="buyconfirm"),
    path('buylist/<custid>/<lpid>/<lname>/<lmodelno>/<lprice>/<ldiscount>/',views.buylist,name="buylist"),
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

online/onlines/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from onlines import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('authen/',include('authen.urls')),
    path('product/',include('product.urls')),
    path('carts/',include('carts.urls')),
    path('',views.welcome,name="welcome")
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

online/product/urls.py
from django.urls import path
from product import views
from django.conf.urls.static import static
from django.conf import settings
app_name='product'
urlpatterns=[
    path('productview/',views.productview,name="productview")
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

online/product/models.py
from unicodedata import category
from django.db import models

# Create your models here.

class productitem(models.Model):
    itemid=models.BigAutoField(primary_key=True)
    itemname=models.CharField(max_length=50)
    def __str__(self):
        return self.itemname
    
class mobilecompany(models.Model):
    comyid=models.BigAutoField(primary_key=True)
    comyname=models.CharField(max_length=50)
    def __str__(self):
        return self.comyname
    
class mobiledetail(models.Model):
    mid=models.BigAutoField(primary_key=True)
    item=models.ForeignKey(productitem,on_delete=models.CASCADE)
    company=models.ForeignKey(mobilecompany,on_delete=models.CASCADE)
    mname=models.CharField(max_length=50)
    mmodelno=models.CharField(max_length=15)
    mdesc=models.TextField(max_length=500)
    imei=models.BigIntegerField()
    mprice=models.FloatField()
    mdiscount=models.FloatField()
    quantity=models.IntegerField()
    mimg=models.ImageField(upload_to='product')
    def __str__(self):
        return self.mname
    
    
class clothcompany(models.Model):
    ccomid=models.BigAutoField(primary_key=True)
    ccomname=models.CharField(max_length=50)
    def __str__(self):
        return self.ccomname
    
    
class clothtype(models.Model):
    ctid=models.BigAutoField(primary_key=True)
    ctname=models.CharField(max_length=50)
    def __str__(self):
        return self.ctname
    
class clothdetail(models.Model):
    cid=models.BigAutoField(primary_key=True)
    citem=models.ForeignKey(productitem,on_delete=models.CASCADE)
    ccompany=models.ForeignKey(mobilecompany,on_delete=models.CASCADE)
    cname=models.CharField(max_length=50)
    cmodelno=models.CharField(max_length=15)
    cdesc=models.TextField(max_length=500)
    ctype=models.ForeignKey(clothtype,on_delete=models.CASCADE)
    lu=[['Male','MALE'],['Female','FEMALE'],['kids','KIDS']]
    category=models.CharField(max_length=15,choices=lu)
    cprice=models.FloatField()
    cdiscount=models.FloatField()
    quantity=models.IntegerField()
    li=[['Small','SMALL'],['Medium','MEDIUM'],['Large','LARGE'],['ExtraLarge','EXTRALARGE'],['DoubleExtra Large','DOUBLEEXTRA LARGE']]
    size=models.CharField(max_length=25,choices=li)
    cimg=models.ImageField(upload_to='cloths')
    def __str__(self):
        return self.cname
    
class grocaryitems(models.Model):
    gid=models.BigAutoField(primary_key=True)
    gitem=models.CharField(max_length=50)
    
    def __str__(self):
        return self.gitem
    
class grocarydetail(models.Model):
    gid=models.BigAutoField(primary_key=True)
    gitem=models.ForeignKey(productitem,on_delete=models.CASCADE)
    gcompany=models.ForeignKey(mobilecompany,on_delete=models.CASCADE)
    groitem=models.ForeignKey(grocaryitems,on_delete=models.CASCADE)
    gname=models.CharField(max_length=50)
    gdesc=models.TextField(max_length=500)
    gprice=models.FloatField()
    gdiscount=models.FloatField()
    quantity=models.IntegerField()
    gimg=models.ImageField(upload_to='grocary')
    def __str__(self):
        return self.gname

    
    
    

online/product/views.py
from django.shortcuts import render
from product.models import mobiledetail
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/authen/login/')
def productview(request):
    res=mobiledetail.objects.all()
    return render(request,'productindex.html',{'res':res})

online/product/templates/productindex.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Product Page</title>

    {% include 'partials/bootcss.html' %}
    {% include 'partials/bootjs.html' %}

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>
  {%include 'partials/_header.html' %}
</header>


<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {%for i in res%}
        <div class="col">
          <div class="card shadow-sm">
          <img width="359 pixels" height="225 pixels" src="{{i.mimg.url}}" alt="{{i.img}}"/>
          <hr class="rounded">
            <div class="card-body">
              <p class="card-text">{{i.mdesc}}</p>
              <hr class="rounded">
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Name: <br>{{i.mname|upper}}</small>
                <small class="text-muted">Model:<br> {{i.mmodelno}}</small>
                <small class="text-muted">Price: <br>{{i.mprice}}</small>
                <small class="text-muted">Discount: <br>{{i.mdiscount}}</small>
              </div>
              <hr class="rounded">
              <div class="btn-group">
                <a href="{% url 'carts:cartlist' custid=12 lpid=i.mid lname=i.mname lmodelno=i.mmodelno lprice=i.mprice ldiscount=i.mdiscount %}"><button class="btn btn-sm btn-outline-secondary">Cart</button></a>
                <a href="#"> <button class="btn btn-sm btn-outline-secondary">Offer</button></a>
                <a href="{% url 'carts:buylist' custid=12 lpid=i.mid lname=i.mname lmodelno=i.mmodelno lprice=i.mprice ldiscount=i.mdiscount %}"><button class="btn btn-sm btn-outline-primary">Buy</button></a>

              </div>
            </div>
          </div>
        </div>
        {%endfor%}
      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="../getting-started/introduction/">getting started guide</a>.</p>
    
  </div>
</footer>      
  </body>
</html>