online/authen/urls.py
from django.urls import path
from authen import views
from django.conf.urls.static import static
from django.conf import settings
app_name='authen'
urlpatterns=[
    path('register/',views.registerview,name="register"),
    path('login/',views.loginview,name="login"),
    path('home/',views.home,name="home"),
    path('logout/',views.logoutview,name="logout"),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

online/carts/urls.py
from django.urls import path
from carts import views
from django.conf.urls.static import static
from django.conf import settings
app_name='carts'
urlpatterns=[
    path('cartindex/',views.cartview,name="cartindex"),
    path('cartlist/<custid>/<lpid>/<lname>/<lmodelno>/<lprice>/<ldiscount>/',views.cartlist,name="cartlist"),
    path('cancelitem/<pk>/',views.cancelitem,name="cancelitem"),
    path('bill/',views.billing,name="bill"),
    path('confirmbill/',views.confirmbill,name="confirmbill"),
    path('buyconfirm/',views.buyconfirm,name="buyconfirm"),
    path('buylist/<custid>/<lpid>/<lname>/<lmodelno>/<lprice>/<ldiscount>/',views.buylist,name="buylist"),
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

online/onlines/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from onlines import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('authen/',include('authen.urls')),
    path('product/',include('product.urls')),
    path('carts/',include('carts.urls')),
    path('',views.welcome,name="welcome")
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

online/product/urls.py
from django.urls import path
from product import views
from django.conf.urls.static import static
from django.conf import settings
app_name='product'
urlpatterns=[
    path('productview/',views.productview,name="productview")
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

online/authen/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class registermodel(User):
    age=models.IntegerField()
    li=[['Male','MALE'],['Female','FEMALE']]
    gender=models.CharField(max_length=10,choices=li)
    phone=models.BigIntegerField(unique=True)
    address=models.CharField(max_length=150)
    
    
        
    
    
    

online/authen/forms.py
from xml.dom.minidom import Attr
from django.contrib.auth.forms import UserCreationForm
from django import forms
from authen.models import registermodel
from django.contrib.auth.hashers import make_password
class registerform(forms.ModelForm):
    class Meta:
        model=registermodel
        fields=['username','first_name','last_name','password','age','gender','email','phone','address']
        widgets={'password':forms.PasswordInput,}
    def clean_phone(self):
        res=self.cleaned_data['phone']
        if len(str(res))!=10:
            raise forms.ValidationError('Phone number should be 10 digits')
        return res
    def clean_age(self):
        age=self.cleaned_data['age']
        if age<=15:
            raise forms.ValidationError('age should be above 15 years')
        elif age>=85:
            raise forms.ValidationError('age should be below 85 years')
        return age
    def save(self, commit=True):
        user=super(registerform,self).save(commit=False)
        user.password=make_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user
            
            
        

online/authen/views.py
from django.shortcuts import render,redirect
from authen.forms import registerform
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import User
# Create your views here.

def registerview(request):
    form=registerform()
    if request.method=='POST':
        form=registerform(request.POST)
        if form.is_valid():
            form.save()
            user= form.cleaned_data['first_name']
            send_mail(subject="Haii welcome to my online shopping",
                      message="Mr/Ms {}, Thank you for registering in my online shopping".format(user),
                      from_email=settings.EMAIL_HOST_USER,
                      recipient_list=[form.cleaned_data['email']])
            messages.success(request,"Haii, Mr/Ms.{} registeration is successfully".format(user.title()))
            return redirect('/authen/login/')
    return render(request,'register.html',{'form':form})

def loginview(request):
    if request.method=='POST':
        user=request.POST['username']
        pass1=request.POST['password']
        user1=authenticate(username=user,password=pass1)
        res=User.objects.get(username=user1)
        if user1:
            login(request,user1)
            send_mail(subject="Haii welcome to my online shopping",
                      message="Mr/Ms {}, Thank you for login in my online shopping".format(user),
                      from_email=settings.EMAIL_HOST_USER,
                      recipient_list=[res.email])
            messages.success(request,"Haii, Mr/Ms.{} login is successfully".format(user1))
            return redirect('/authen/home/')
        else:
            messages.error(request,"login cerditals is not there")
    return render(request,'login.html')

@login_required(login_url='/authen/login/')
def home(request):
    return render(request,'homepage.html')

@login_required(login_url='/authen/login/')
def logoutview(request):
    logout(request)
    return redirect('/welcome')
    

online/authen/templates/partials/_header.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    {% block title%}
    <title>header page</title>
    {% endblock %}

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/headers/">
    <!-- Bootstrap core CSS -->
    {% include "partials/bootcss.html" %}

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{%static 'css/headers.css' %}" rel="stylesheet">
  </head>
  <body>
    
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
  </symbol>
  <symbol id="home" viewBox="0 0 16 16">
    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
  </symbol>
  <symbol id="speedometer2" viewBox="0 0 16 16">
    <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
    <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
  </symbol>
  <symbol id="table" viewBox="0 0 16 16">
    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>
  </symbol>
  <symbol id="people-circle" viewBox="0 0 16 16">
    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
  </symbol>
  <symbol id="grid" viewBox="0 0 16 16">
    <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
  </symbol>
</svg>

{%if user.is_authenticated %}
<main>
  <header>
    <div class="row px-3 py-6 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-left justify-content-left justify-content-lg-start">
          <nav class="navbar bg-dark text-white ">
            <a class="navbar-brand" href="#"></a>
            <div class="view overlay zoom">
              <img src="{% static 'images/download1.jfif' %}" width="50" height="50" class="img-fluid rounded form-left align-top" alt="smaple image">
              {{user|title}}
            </div>
          </a>
        </nav>
         <div class="col">
           </div>
          <ul class="nav col-auto col-lg-auto my-auto justify-content-center my-md-auto text-small">
            <li>
              <a href="{%url 'authen:home' %}" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"/></svg>
                Home
              </a>
            </li>
            <li>
              <a href="{%url 'product:productview' %}" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"/></svg>
                Products
              </a>
            </li>
            <li>
              <a href="{%url 'carts:cartindex' %}" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#table"/></svg>
                Cart
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#speedometer2"/></svg>
                Orders
              </a>
            </li> 
            <li>
                <form class="col-auto col-lg-auto mb-auto mb-lg-auto me-lg-auto">
                    <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
                  </form>
            </li>
            <li>
              <a href="{% url 'authen:logout'%}" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#people-circle"/></svg>
                Logout
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    {%else%}
            <h1>{{unknown}}</h1>
    {%endif%}
  </header>

</main>
  </body>
</html>

online/authen/templates/partials/bootcss.html
{% load static %}

<link href="{% static 'boot/css/bootstrap-grid.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-grid.min.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-grid.rtl.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-grid.rtl.min.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-reboot.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-reboot.min.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-reboot.rtl.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-reboot.rtl.min.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-utilities.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-utilities.min.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-utilities.rtl.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap-utilities.rtl.min.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap.rtl.css' %}" rel='stylesheet' type='text/css'>
<link href="{% static 'boot/css/bootstrap.rtl.min.css' %}" rel='stylesheet' type='text/css'>

online/authen/templates/partials/bootjs.html
{% load static %}
<script src="{% static 'boot/js/bootstrap.bundle.js'%}"  type="text/javascript"></script>
<script src="{% static 'boot/js/bootstrap.bundle.min.js'%}"  type="text/javascript"></script>
<script src="{% static 'boot/js/bootstrap.esm.js'%}"  type="text/javascript"></script>
<script src="{% static 'boot/js/bootstrap.esm.min.js'%}"  type="text/javascript"></script>
<script src="{% static 'boot/js/bootstrap.js'%}"  type="text/javascript"></script>
<script src="{% static 'boot/js/bootstrap.min.js'%}"  type="text/javascript"></script>